name: Bug Report
description: Create a report to help us improve.
title: "fix: "
labels: ["fix"]
assignees:
    - gowizzard
body:
    - type: markdown
      attributes:
        value: |
            Please fill in all fields for your bug report carefully so that it can be processed under the best possible conditions.
    - type: textarea
      id: which-error
      attributes:
        label: What error has occurred?
        description: Describe the error in as much detail as possible.
        placeholder: "An error has occurred because..."
      validations:
        required: true