name: Feature Request
description: Create a new feature request to help us improve.
title: "feat: "
labels: ["feature"]
assignees:
    - gowizzard
body:
    - type: markdown
      attributes:
        value: |
            Please fill in all fields for the feature request carefully so that they can be processed under the best possible conditions.
    - type: textarea
      id: which-feature
      attributes:
        label: Which feature would you like to suggest?
        description: Describe the feature in as much detail as possible.
        placeholder: "I want the feature because..."
      validations:
        required: true